"use client";

import { useState, useEffect } from "react";
import MDEditor from "@uiw/react-md-editor";
import { motion, AnimatePresence } from "framer-motion";
import { Sparkles, Terminal, FileText, AlertTriangle, Info } from "lucide-react";

const OutputDisplay = ({ output, active, warnings = {} }) => {
  const [activeTab, setActiveTab] = useState(active);

  useEffect(() => {
    setActiveTab(active);
  }, [active]);

  const tabs = [
    { 
      id: "review", 
      label: "Code Review", 
      icon: Terminal,
      content: output.review,
      warning: warnings.review,
      color: "cyan"
    },
    {
      id: "simple",
      label: "Quick Summary",
      icon: Sparkles,
      content: output.explanationSimple,
      warning: warnings.explanationSimple,
      color: "purple"
    },
    {
      id: "technical",
      label: "Deep Dive",
      icon: FileText,
      content: output.explanationTechnical,
      warning: warnings.explanationTechnical,
      color: "pink"
    },
  ];

  const availableTabs = tabs.filter((tab) => tab.content);

  if (availableTabs.length === 0) return null;

  return (
    <div className="w-full max-w-5xl mx-auto space-y-6">
      {/* Premium Tabs */}
      <div className="flex p-1.5 bg-white/5 backdrop-blur-xl rounded-[2rem] border border-white/10">
        {availableTabs.map((tab) => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id)}
            className={`flex-1 py-4 px-6 rounded-[1.5rem] flex items-center justify-center gap-3 transition-all relative group ${
              activeTab === tab.id 
                ? "bg-white/10 text-white shadow-xl" 
                : "text-white/40 hover:text-white/60"
            }`}
          >
            <tab.icon className={`w-4 h-4 transition-colors ${
              activeTab === tab.id 
                ? (tab.color === 'cyan' ? 'text-cyan-400' : tab.color === 'purple' ? 'text-purple-400' : 'text-pink-400') 
                : ""
            }`} />
            <span className="font-bold text-sm tracking-tight">{tab.label}</span>
            {activeTab === tab.id && (
              <motion.div 
                layoutId="activeOutputTab" 
                className={`absolute bottom-2 w-1.5 h-1.5 rounded-full ${
                  tab.color === 'cyan' ? 'bg-cyan-400' : tab.color === 'purple' ? 'bg-purple-400' : 'bg-pink-400'
                }`} 
              />
            )}
          </button>
        ))}
      </div>

      {/* Output Content */}
      <AnimatePresence mode="wait">
        {availableTabs.map((tab) => (
          activeTab === tab.id && (
            <motion.div
              key={tab.id}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              className="glass-card rounded-[2.5rem] border border-white/10 overflow-hidden shadow-2xl"
            >
              <div className={`absolute inset-0 bg-gradient-to-br from-${tab.color}-500/5 to-transparent z-0 pointer-events-none`}></div>
              
              <div className="relative z-10 p-8 md:p-12">
                {tab.warning && (
                  <div className="bg-yellow-500/10 border border-yellow-500/20 rounded-2xl p-5 mb-8 flex items-start gap-4">
                    <div className="w-10 h-10 rounded-xl bg-yellow-500/20 flex items-center justify-center border border-yellow-500/30 shrink-0">
                      <AlertTriangle className="w-5 h-5 text-yellow-400" />
                    </div>
                    <div className="space-y-1">
                      <p className="text-sm font-bold text-yellow-400 uppercase tracking-widest">AI Limitation Notice</p>
                      <p className="text-yellow-200/70 text-sm font-medium">
                        {tab.warning}
                      </p>
                    </div>
                  </div>
                )}

                <div className="markdown-output prose prose-invert max-w-none">
                  <MDEditor.Markdown
                    source={tab.content}
                    className="!bg-transparent !text-white/80"
                  />
                </div>

                <div className="mt-12 pt-8 border-t border-white/5 flex items-center justify-between text-white/20">
                   <div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[0.3em]">
                     <Info className="w-3 h-3" />
                     Generated by CareerForge Code Reviewer
                   </div>
                </div>
              </div>
            </motion.div>
          )
        ))}
      </AnimatePresence>
    </div>
  );
};

export default OutputDisplay;